// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitPoint() *Point {
	point := _wirePointValue
	return point
}

var (
	_wirePointValue = &Point{
		X: 1,
		Y: 2,
	}
)
