// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitGreeter() *Greeter {
	mainTypeA := _wireTypeAValue
	mainTypeB := _wireTypeBValue
	options := &Options{
		A: mainTypeA,
		B: mainTypeB,
	}
	greeter := NewGreeter(options)
	return greeter
}

var (
	_wireTypeAValue = typeA(10)
	_wireTypeBValue = typeB(20)
)

// wire.go:

type typeA int

type typeB int

type Options struct {
	A typeA
	B typeB
}

type Greeter struct {
	AAA typeA
	BBB typeB
}

func NewGreeter(opts *Options) *Greeter {

	return &Greeter{
		AAA: opts.A,
		BBB: opts.B,
	}
}

var GreeterSet = wire.NewSet(wire.Struct(new(Options), "*"), NewGreeter)
